name: Bug

description: Report a defect.

title: "[Bug] "

body:
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser/device/OS/app version.
